// Türkçe 5 harfli kelime listesi (otomatik süzüldü, tam 5 harf).
const List<String> kWords = [
  'akşam', 'altın', 'antma', 'araba', 'armut', 'asker',
  'aslan', 'bahçe', 'bakır', 'balık', 'banka', 'banyo',
  'bağır', 'bebek', 'beton', 'beyaz', 'beyin', 'biber',
  'bulut', 'buzul', 'börek', 'cadde', 'ceket', 'ciğer',
  'damar', 'davul', 'demir', 'deniz', 'dolap', 'donma',
  'dudak', 'duvar', 'dünya', 'düşün', 'ekmek', 'ekran',
  'erkek', 'forma', 'fırça', 'fırın', 'galip', 'gitar',
  'gurur', 'gümüş', 'güney', 'güneş', 'hasta', 'havuç',
  'hayal', 'hesap', 'huzur', 'hüzün', 'incir', 'insan',
  'kabak', 'kadın', 'kalem', 'kapak', 'karar', 'kavun',
  'kağıt', 'kaşık', 'keman', 'kemer', 'kemik', 'kilit',
  'kiraz', 'kitap', 'komşu', 'korku', 'kredi', 'kumaş',
  'kural', 'kuzey', 'köfte', 'köpek', 'köprü', 'lamba',
  'makas', 'marul', 'merak', 'metro', 'meyve', 'motor',
  'mutlu', 'müzik', 'orman', 'oyunu', 'palto', 'pamuk',
  'pasta', 'pembe', 'perde', 'pilav', 'polis', 'resim',
  'reçel', 'roman', 'sabah', 'salon', 'salça', 'sebze',
  'sepet', 'serin', 'sevgi', 'silgi', 'simit', 'sinek',
  'sinir', 'siyah', 'sokak', 'soğan', 'soğuk', 'sıcak',
  'sınav', 'sınıf', 'tabak', 'tahta', 'taksi', 'takım',
  'tarih', 'tatlı', 'tavan', 'terzi', 'tohum', 'tuval',
  'tuğla', 'utanç', 'vapur', 'yatak', 'yaşlı', 'yemek',
  'yenik', 'yeşil', 'yılan', 'zafer', 'zaman', 'çadır',
  'çanta', 'çatal', 'çelik', 'çimen', 'çiçek', 'çocuk',
  'çorap', 'çorba', 'çörek', 'şapka', 'şarkı', 'şehir',
  'şeker', 'şüphe',
];
